name: STMFun
version: '0.1.0.0'
category: Miscellanous
author: Christian Kjaer Laustsen
maintainer: ckl@codetalk.io
copyright: Christian Kjaer Laustsen
license: BSD3
extra-source-files:
- README.md

dependencies:
- base
- stm
- lifted-async
- say
- lens
- mtl
- containers
- haskeline
- unliftio

library:
  source-dirs: src

executables:
  Test-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - STMFun

tests:
  Test-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - STMFun
